autoindex:
  params:
    build: '{"M": 18,"efConstruction": 240,"index_type": "HNSW", "metric_type": "IP"}'
    search: ""
    tuning: ""
common:
  channameprefix:
    cluster: by-dev
    datacoordsegmentinfo: segment-info-channel
    datacoordstatistic: datacoord-statistics-channel
    datacoordtimetick: datacoord-timetick-channel
    querytimetick: queryTimeTick
    rootcoorddelta: rootcoord-delta
    rootcoorddml: rootcoord-dml
    rootcoordstatistics: rootcoord-statistics
    rootcoordtimetick: rootcoord-timetick
    search: search
    searchresult: searchResult
  defaultindexname: _default_idx
  defaultpartitionname: _default
  diskindex:
    beamwidthratio: 4
    buildnumthreadsratio: 1
    loadnumthreadratio: 8
    maxdegree: 56
    pqcodebudgetgbratio: 0.125
    searchcachebudgetgbratio: 0.1
    searchlistsize: 100
  entityexpiration: -1
  gracefulstoptimeout: 1800
  gracefultime: 5000
  importmaxfilesize: 17179869184
  indexslicesize: 16
  locks:
    metrics:
      enable: false
    threshold:
      info: 500
      warn: 1000
  precreatedtopic:
    enabled: false
    names:
    - topic1
    - topic2
    timeticker: timetick-channel
  retentionduration: 0
  security:
    authorizationenabled: false
    tlsmode: 0
  session:
    retrytimes: 30
    ttl: 60
  simdtype: auto
  storagetype: minio
  subnameprefix:
    datacoordsubnameprefix: dataCoord
    datanodesubnameprefix: dataNode
    proxysubnameprefix: proxy
    querynodesubnameprefix: queryNode
    rootcoordsubnameprefix: rootCoord
  threadcorecoefficient:
    highpriority: 10
    lowpriority: 1
    middlepriority: 5
datacoord:
  channel:
    balanceinterval: 360
    balancesilentduration: 300
    watchtimeoutinterval: 300
  compaction:
    enableautocompaction: true
    indexbasedcompaction: true
    maxparalleltasknum: 100
    rpctimeout: 10
  enableactivestandby: false
  enablecompaction: true
  enablegarbagecollection: true
  gc:
    droptolerance: 10800
    interval: 3600
    missingtolerance: 3600
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  port: 13333
  segment:
    assignmentexpiration: 2000
    compactableproportion: 0.85
    disksegmentmaxsize: 2048
    expansionrate: 1.25
    maxbinlogfilenumber: 32
    maxidletime: 600
    maxlife: 86400
    maxsize: 512
    minsizefromidletosealed: 16
    sealproportion: 0.23
    smallproportion: 0.5
datanode:
  datasync:
    flowgraph:
      maxparallelism: 1024
      maxqueuelength: 16
    maxparallelsynctasknum: 6
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  memory:
    forcesyncenable: true
    forcesyncsegmentnum: 1
    watermarkcluster: 0.5
    watermarkstandalone: 0.2
  port: 21124
  segment:
    deletebufbytes: 67108864
    insertbufsize: 16777216
    syncperiod: 600
  timetick:
    byrpc: true
etcd:
  data:
    dir: default.etcd
  endpoints: localhost:2379
  kvsubpath: kv
  log:
    level: info
    path: stdout
  metasubpath: meta
  rootpath: by-dev
  ssl:
    enabled: false
    tlscacert: /path/to/ca.pem
    tlscert: /path/to/etcd-client.pem
    tlskey: /path/to/etcd-client-key.pem
    tlsminversion: 1.3
  use:
    embed: false
grpc:
  client:
    backoffmultiplier: 2
    compressionenabled: false
    dialtimeout: 200
    initialbackoff: 1
    keepalivetime: 10000
    keepalivetimeout: 20000
    maxbackoff: 10
    maxmaxattempts: 5
  clientmaxrecvsize: 268435456
  clientmaxsendsize: 268435456
  log:
    level: WARNING
  servermaxrecvsize: 536870912
  servermaxsendsize: 536870912
indexcoord:
  bindindexnodemode:
    address: localhost:22930
    enable: false
    nodeid: 0
    withcred: false
  segment:
    minsegmentnumrowstoenableindex: 1024
indexnode:
  enabledisk: true
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  maxdiskusagepercentage: 95
  port: 21121
  scheduler:
    buildparallel: 1
localstorage:
  path: /var/lib/milvus/data/
log:
  file:
    maxage: 10
    maxbackups: 20
    maxsize: 300
  format: text
  level: info
  stdout: true
metastore:
  type: etcd
minio:
  accesskeyid: minioadmin
  address: localhost
  bucketname: a-bucket
  cloudprovider: aws
  loglevel: error
  port: 9000
  region: ""
  rootpath: files
  secretaccesskey: minioadmin
  useiam: false
  usessl: false
  usevirtualhost: false
mq:
  type: default
natsmq:
  server:
    initializetimeout: 4000
    maxfilestore: 17179869184
    maxpayload: 8388608
    maxpending: 67108864
    monitor:
      debug: false
      logfile: /tmp/milvus/logs/nats.log
      logsizelimit: 536870912
      logtime: true
      trace: false
    port: 4222
    retention:
      maxage: 4320
    storedir: /var/lib/milvus/nats
proxy:
  accesslog:
    filename: milvus_access_log.log
    localpath: /tmp/milvus_accesslog
  ginlogging: true
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 67108864
    servermaxsendsize: 67108864
  healthchecktimetout: 3000
  http:
    debug_mode: false
    enabled: true
  internalport: 19529
  maxdimension: 32768
  maxfieldnum: 64
  maxnamelength: 255
  maxshardnum: 16
  maxtasknum: 1024
  msgstream:
    timetick:
      bufsize: 512
  port: 19530
  timetickinterval: 200
pulsar:
  address: localhost
  maxmessagesize: 5242880
  namespace: default
  port: 6650
  requesttimeout: 60
  tenant: public
  webport: 80
querycoord:
  autobalance: true
  autohandoff: true
  balanceintervalseconds: 60
  balancer: ScoreBasedBalancer
  brokertimeout: 5000
  channeltasktimeout: 60000
  checkhandoffinterval: 5000
  checkinterval: 1000
  distpullinterval: 500
  enableactivestandby: false
  globalrowcountfactor: 0.1
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  heartbeatavailableinterval: 10000
  loadtimeoutseconds: 600
  memoryusagemaxdifferencepercentage: 30
  overloadedmemorythresholdpercentage: 90
  port: 19531
  reverseunbalancetolerationfactor: 1.3
  scoreunbalancetolerationfactor: 0.05
  segmenttasktimeout: 120000
  taskexecutioncap: 256
  taskmergecap: 1
querynode:
  cache:
    enabled: true
    memorylimit: 2147483648
  datasync:
    flowgraph:
      maxparallelism: 1024
      maxqueuelength: 16
  enabledisk: false
  grouping:
    enabled: true
    maxnq: 1000
    topkmergeratio: 20
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  loadmemoryusagefactor: 1
  maxdiskusagepercentage: 95
  port: 21123
  scheduler:
    cpuratio: 10
    maxreadconcurrentratio: 1
    maxtimestamplag: 86400
    receivechansize: 10240
    schedulereadpolicy:
      enablecrossusergrouping: false
      maxpendingtask: 10240
      maxpendingtaskperuser: 1024
      name: fifo
      taskqueueexpire: 60
    unsolvedqueuesize: 10240
  segcore:
    cgopoolsizeratio: 2
    chunkrows: 1024
    growing:
      enableindex: true
      nlist: 128
      nprobe: 16
    knowherethreadpoolnumratio: 4
  stats:
    publishinterval: 1000
quotaandlimits:
  compactionrate:
    enabled: false
    max: -1
  ddl:
    collectionrate: -1
    enabled: false
    partitionrate: -1
  dml:
    bulkloadrate:
      collection:
        max: -1
      max: -1
    deleterate:
      collection:
        max: -1
      max: -1
    enabled: false
    insertrate:
      collection:
        max: -1
      max: -1
    upsertrate:
      collection:
        max: -1
      max: -1
  dql:
    enabled: false
    queryrate:
      collection:
        max: -1
      max: -1
    searchrate:
      collection:
        max: -1
      max: -1
  enabled: true
  flushrate:
    enabled: false
    max: -1
  indexrate:
    enabled: false
    max: -1
  limitreading:
    cooloffspeed: 0.9
    forcedeny: false
    queueprotection:
      enabled: false
      nqinqueuethreshold: -1
      queuelatencythreshold: -1
    resultprotection:
      enabled: false
      maxreadresultrate: -1
  limits:
    maxcollectionnum: 65536
    maxcollectionnumperdb: 65536
  limitwriting:
    diskprotection:
      diskquota: -1
      diskquotapercollection: -1
      enabled: true
    forcedeny: false
    growingsegmentssizeprotection:
      enabled: false
      highwaterlevel: 0.4
      lowwaterlevel: 0.2
      minrateratio: 0.5
    memprotection:
      datanodememoryhighwaterlevel: 0.95
      datanodememorylowwaterlevel: 0.85
      enabled: true
      querynodememoryhighwaterlevel: 0.95
      querynodememorylowwaterlevel: 0.85
    ttprotection:
      enabled: false
      maxtimetickdelay: 300
  quotacentercollectinterval: 3
rocksmq:
  compactioninterval: 86400
  compressiontypes:
  - 0
  - 0
  - 7
  - 7
  - 7
  lrucacheratio: 0.06
  path: /var/lib/milvus/rdb_data
  retentionsizeinmb: 8192
  retentiontimeinminutes: 4320
  rocksmqpagesize: 67108864
rootcoord:
  dmlchannelnum: 16
  enableactivestandby: false
  grpc:
    clientmaxrecvsize: 268435456
    clientmaxsendsize: 268435456
    servermaxrecvsize: 536870912
    servermaxsendsize: 536870912
  importtaskexpiration: 900
  importtaskretention: 86400
  maxdatabasenum: 64
  maxpartitionnum: 4096
  minsegmentsizetoenableindex: 1024
  port: 53100
tls:
  capempath: configs/cert/ca.pem
  serverkeypath: configs/cert/server.key
  serverpempath: configs/cert/server.pem
trace:
  exporter: stdout
  samplefraction: 0
